name = "workers-graphql-server"
type = "webpack"

account_id = "f4a67da6bfae8c7b4048439922a6b12b"
zone_id = "cbc52359836a8ef5bc56e5196e596d23"
route = "solide.fi/api"

workers_dev = true
webpack_config = "webpack.config.js"
compatibility_date = "2021-10-03"

# Enable a kv-namespace to use the KV caching feature
#
# kv-namespaces = [
#   { binding = "WORKERS_GRAPHQL_CACHE", id = "" }
# ]

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./src/index.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"
